sudo: required

dist: trusty

language: node_js

node_js:
- 8
- 9

branches:
  only:
  - master
  - staging

cache:
  directories:
  - node_modules

addons:
  chrome: stable

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm config set spin false

jobs:
  include:

    - stage: compile
      script: ng build --prod

    - stage: E2E
      script: npm run e2e

    - stage: coverage
      script:
        - npm run test:coverage
        - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

    - stage: deploy to staging
      before_script: npm install -g firebase-tools
      script: ng build --prod --env=dev
      after_success: firebase deploy --only hosting -P staging --token $FIREBASE_TOKEN

    - stage: deploy to production
      if: branch = master
      before_script: npm install -g firebase-tools
      script: npm run pwa
      after_success: firebase deploy --only hosting -P prod --token $FIREBASE_TOKEN

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
  slack: eventpicking:jb0vuR0xTQzpICYBCkDVEYWI